name: flutter_template_simple
description: "A new Flutter project about flutter_template_simple"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.0
  haptic_feedback: ^0.5.1+1
  hexcolor: ^3.0.1
  home_widget: ^0.5.0
  image: ^4.2.0
  image_picker: ^1.1.2
  image_watermark: ^0.1.0
  intl: ^0.18.1
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  swipeable_page_route: ^0.4.2
  timeline_list: ^0.0.6
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/ # 子目录的路径也要写上，或者指定为目标文件的路径
    - assets/common/ # 子目录的路径也要写上，或者指定为目标文件的路径
flutter_intl:
  enabled: true
